### ISSUE TITLE
MS-LPL? Don't you mean MS-PL?

### ISSUE THREAD

**Issue by Jaykul** [adbertram/PSSoftware#10]
Are you sure you mean to license this with a term (3F) that requires use on Windows?

Or is it because you're using components licensed that way?

If you switch to [MS-PL](https://opensource.org/licenses/MS-PL) it removes (just) that clause ... but if it's all _your_ code, maybe you could switch to MIT to match PowerShell Core's license?

**Comment by adbertram** [comment]
I didn't even realize a license was set. If there was a "do whatever the hell you want with this license", I'd like to pick that.
