### ISSUE TITLE
Module does not import in PowerShell v2

### ISSUE THREAD

**Issue by corbob** [adbertram/PSSoftware#11]
On Windows 10 (Powershell.exe -v 2) Module fails to import:

![image](https://user-images.githubusercontent.com/30301021/39629589-928e1890-4f61-11e8-9c9c-381ea0548059.png)

Removing the RootModule from the PSD1 results in a module with no exported commands.

Should we remove the PSv2 support from the readme?

**Comment by adbertram** [comment]
Yep. Removed. Thank you.
