### ISSUE TITLE
Get-InstalledSoftware failed due to call depth overflow

### ISSUE THREAD

**Issue by fullenw1** [adbertram/PSSoftware#8]
# The error:
PS C:\Windows\system32> Get-InstalledSoftware
Write-Log :
**The script failed due to call depth overflow.
    + CategoryInfo          : InvalidOperation: (0:Int32) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CallDepthOverflow**

PS C:\Windows\system32>

# For information:
`PS C:\Windows\system32> $PSVersionTable

Name                           Value
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

PS C:\Windows\system32> gwmi -class win32_operatingsystem|select -Property version,buildnumber,caption

version  buildnumber caption
6.1.7601 7601        Microsoft Windows 7 Enterprise

PS C:\Windows\system32>`

**Comment by adbertram** [comment]
Could you include the log file? It should be in C:\Windows\Temp\SoftwareInstallManager.log

**Comment by fullenw1** [comment]
I can't find any log file.
I event searched for files written in the last minutes on the whole drive...

**Comment by fullenw1** [comment]
Hi Adam,

I finally found the reason of this issue.
In fact, I didn't realize that at home I was using the old module named **SoftwareInstallManager**.
And at office I am using the **PSSoftware** module.
That's why I didn't have any problem at work.

Regarding the **SoftwareInstallManager** version,
the `Write-Log` function has a line with `Write-Log`
(instead of `Write-Verbose` like it's the case in the new module),
and thus calling itself in a infinite loop,
which leads to the depth overflow error described above.

Maybe you can disable the old module because it is still available on PowershellGallery.

Thank you again for sharing so useful code.
I use `Get-InstalledSoftware` and `Uninstall-WindowsInstallerPackage*` very often.
